
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import java.util.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Calendar;

public class HotelSearchGUI extends javax.swing.JPanel {
    
    List<String> checkInDayList = new ArrayList<String>(); 
    List<String> checkOouDayList = new ArrayList<String>(); 
    private String CheckInDays, CheckOutDays;
    private String RoomsType;
    private int rooms = 0,  adults = 0;
    private String City, Hotels; 
    Connection con = null;
    List<String> cityList = new ArrayList<String>();

    public String getRoomsType() {
        return RoomsType;
    }

    public void setRoomsType(String RoomsType) {
        this.RoomsType = RoomsType;
    }

    public String getCheckInDays() {
        return CheckInDays;
    }

    public void setCheckInDays(String CheckInDays) {
        this.CheckInDays = CheckInDays;
    }

    public String getCheckOutDays() {
        return CheckOutDays;
    }

    public void setCheckOutDays(String CheckOutDays) {
        this.CheckOutDays = CheckOutDays;
    }

    public int getRooms() {
        return rooms;
    }

    public void setRooms(int rooms) {
        this.rooms = rooms;
    }

    public int getAdults() {
        return adults;
    }

    public void setAdults(int adults) {
        this.adults = adults;
    }

    public String getCity() {
        return City;
    }

    public void setCity(String City) {
        this.City = City;
    }

    public String getHotels() {
        return Hotels;
    }

    public void setHotels(String Hotels) {
        this.Hotels = Hotels;
    }

    /**
     * Creates new form HotelSearchGUI
     */
    public HotelSearchGUI(Connection con) {
        initComponents();
        this.con = con;
        this.setCityHotelList();
    }

    /* set City / hotels */
   
    public void setCityHotelList()
    {  
       try
       {
          String sql = "SELECT * from city";
            
          Statement st = con.createStatement();
          ResultSet rs;
            
          rs = st.executeQuery(sql);
          
          //Reading list of cities from Database and save the data into cityList
          while(rs.next())
          {
              String element = rs.getString(1); // + "--" + rs.getString(2);
              
              cityList.add(element);              
          }
       }
       catch(SQLException e)
       {
          e.printStackTrace();
       }
       
       //Set Jcombobox1 list to cityList 
       CityBox.removeAllItems();       
       for (String s : cityList) 
       {
         CityBox.addItem(s);
       } 
       
       //HotelBox.removeAllItems();       
       //for (String s : cityList) 
      // {
        // CityBox.addItem(s);
       //} 
       
    }
    
    /*Set Number Reserve Rooms notification*/
    public boolean NumRoom()
    {
        boolean acceptable;
        
        if ( Integer.parseInt(CheckOutDate.getSelectedItem().toString()) <= 0 )
        {
            acceptable = false;
            JOptionPane.showMessageDialog(null,
                "Select Room!");
        }
        else
        acceptable = true;
        
        return acceptable;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CheckInYear = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        NumPerson = new javax.swing.JComboBox();
        CheckOutYear = new javax.swing.JComboBox();
        CheckInMonth = new javax.swing.JComboBox();
        CheckOutDate = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        NumRoom = new javax.swing.JComboBox();
        CheckInDate = new javax.swing.JComboBox();
        ErrorLabelValid = new javax.swing.JLabel();
        RoomType = new javax.swing.JComboBox();
        SearchHotelButton = new javax.swing.JButton();
        HotelBox = new javax.swing.JComboBox();
        CheckOutMonth = new javax.swing.JComboBox();
        CityBox = new javax.swing.JComboBox();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Hotels");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Check out");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Check in ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Rooms");

        jLabel5.setText("Year");

        jLabel6.setText("Month");

        CheckInYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017" }));

        jLabel7.setText("Date");

        jLabel8.setText("Year");

        jLabel9.setText("Month");

        jLabel10.setText("Date");

        jLabel11.setBackground(new java.awt.Color(0, 0, 204));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Location - City");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Adults");

        NumPerson.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        CheckOutYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017" }));

        CheckInMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "Feburay", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        CheckOutDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Type");

        NumRoom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        CheckInDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        RoomType.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        RoomType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "King", "Queens", "Suite" }));
        RoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomTypeActionPerformed(evt);
            }
        });

        SearchHotelButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SearchHotelButton.setText("Search Hotels");
        SearchHotelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchHotelButtonActionPerformed(evt);
            }
        });

        HotelBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        HotelBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Holiday Inn", "Best Western", "La Quinta" }));

        CheckOutMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "Feburay", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        CityBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchHotelButton)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(340, 340, 340))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheckOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CheckInYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CheckInMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(CityBox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(ErrorLabelValid))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HotelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NumPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CheckOutYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CheckOutMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(NumRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(68, 68, 68)
                                        .addComponent(jLabel12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CheckInDate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(120, 120, 120))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(ErrorLabelValid)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HotelBox)
                    .addComponent(CityBox))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(CheckInYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(CheckInMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(CheckOutYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(CheckOutMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(NumPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel13)
                                .addComponent(jLabel12))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NumRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CheckInDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(65, 65, 65)
                .addComponent(SearchHotelButton)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SearchHotelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchHotelButtonActionPerformed
        // TODO add your handling code here:
         //Setting departureAiport to airport code of departure
        City = CityBox.getSelectedItem().toString();
        Hotels = HotelBox.getSelectedItem().toString();
        rooms = Integer.parseInt(NumRoom.getSelectedItem().toString());
        adults = Integer.parseInt(NumPerson.getSelectedItem().toString());
        RoomsType = RoomType.getSelectedItem().toString();
       
        int CIyear = Integer.parseInt(CheckInYear.getSelectedItem().toString());
        int CImonth = Integer.parseInt(CheckInMonth.getSelectedItem().toString());
        int CIdate = Integer.parseInt(CheckInDate.getSelectedItem().toString());
        int COyear = Integer.parseInt(CheckOutYear.getSelectedItem().toString());
        int COmonth = Integer.parseInt(CheckOutMonth.getSelectedItem().toString());
        int COdate = Integer.parseInt(CheckOutDate.getSelectedItem().toString());
        CheckInDays = CheckInYear.getSelectedItem().toString() + Integer.parseInt(CheckInMonth.getSelectedItem().toString())+Integer.parseInt(CheckInDate.getSelectedItem().toString());
        CheckOutDays = CheckOutYear.getSelectedItem().toString() + Integer.parseInt(CheckOutMonth.getSelectedItem().toString())+Integer.parseInt(CheckOutDate.getSelectedItem().toString());
        
        HotelSearch findhotel = new HotelSearch( con, 
                        this.getCity(),
                        this.getHotels(), 
                        this.getRoomsType(),
                        this.getCheckInDays(),
                        this.getCheckOutDays() ,
                        this.getAdults(),
                        this.getRooms()
                       
                        );
        
        findhotel.findListHotels();
        //this.setVisible(false);
        
    }//GEN-LAST:event_SearchHotelButtonActionPerformed

    private void RoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CheckInDate;
    private javax.swing.JComboBox CheckInMonth;
    private javax.swing.JComboBox CheckInYear;
    private javax.swing.JComboBox CheckOutDate;
    private javax.swing.JComboBox CheckOutMonth;
    private javax.swing.JComboBox CheckOutYear;
    private javax.swing.JComboBox CityBox;
    private javax.swing.JLabel ErrorLabelValid;
    private javax.swing.JComboBox HotelBox;
    private javax.swing.JComboBox NumPerson;
    private javax.swing.JComboBox NumRoom;
    private javax.swing.JComboBox RoomType;
    private javax.swing.JButton SearchHotelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
