
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import javax.swing.*;
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lee
 */


public class MainFrame extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {
        initComponents();
    }
   
     
    @Override
    public void actionPerformed(ActionEvent e)
    {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
                
        Database db = new Database();
        Connection con = db.getConnection();
        FlightSearchGUI flightSearchGUI = new FlightSearchGUI(con);
        
        
        //HotelSearchGUI hotelSearch = new HotelSearchGUI(con);
        
        
        
                       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {               
                
                /*
                MainFrame frame = new MainFrame();                
                frame.setSize(800, 570);
                 
                frame.add(flightSearchGUI);
                frame.setVisible(true);
                        */
                
        
        MainFrame frame = new MainFrame();                
        frame.setSize(800, 590);
        
        JPanel contentPane = new JPanel();
        
        contentPane.setSize(800, 590);
        contentPane.add(flightSearchGUI);
                 
        frame.add(contentPane);
        frame.setVisible(true);
        
        flightSearchGUI.jButton1.addActionListener(new ActionListener (){
         public void actionPerformed(ActionEvent e) {  
             Object source = e.getSource();
             if(source == flightSearchGUI.jButton1)
             {
               if(flightSearchGUI.nextStep){
               flightSearchGUI.jButton1ActionPerformed(e);
               ShowFlightSearch showFlightSearch = new ShowFlightSearch(
               flightSearchGUI.findFlight.getDirectList(),
               flightSearchGUI.findFlight.getIndirectList1(),
               flightSearchGUI.findFlight.getIndirectList2(),
               flightSearchGUI.findFlight.getIndirectList3(),
               flightSearchGUI.findFlight.getDirectFlight(),
               con,
               flightSearchGUI.findFlight.getAdultFirst(),
               flightSearchGUI.findFlight.getChildFirst(),
               flightSearchGUI.findFlight.getAdultBusiness(),
               flightSearchGUI.findFlight.getChildBusiness());
              
               
               
               showFlightSearch.setVisible(true);
               contentPane.remove(flightSearchGUI);
               contentPane.add(showFlightSearch);
               frame.add(contentPane);
               frame.setSize(801,591);
               }
            }
          }
         });
        
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    
    
}
